spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: alpha
      tagsSorter: alpha
    api-docs:
      path: /api-docs